import { GRIEVANCE_ROWS, LEGAL_CONTACT_EMAIL, LEGAL_UPDATED } from "./legal";
import type { LegalDoc } from "./legal";

/**
 * Terms of Service, transcribed verbatim from the counsel-issued draft dated
 * 18 August 2026. Clause order and wording are the lawyers' — only the blanks
 * left in that draft are filled here, from the constants in ./legal.ts.
 */
export const TERMS: LegalDoc = {
	eyebrow: "Legal",
	title: "Terms of Service",
	description:
		"The terms governing your access to and use of influenze.ai, the creator discovery and analytics platform operated by Dotme Technologies Private Limited.",
	updated: LEGAL_UPDATED,
	notice: "This document is an electronic record and is generated by a computer system and does not require any physical or digital signatures.",
	preamble: [
		"Welcome to influenze.ai along with its associated sub-domains, sites, applications, platforms, services, features, application programming interfaces (APIs) and tools (as applicable) (collectively “Platform”), owned by Dotme Technologies Private Limited, a company incorporated under the Companies Act, 2013 and having its registered office address at 1612, Ground floor, 7th Cross, 19th Main Road, 1st Sector, HSR Layout, Bengaluru, Karnataka – 560102 (“Company”). The Company is, inter alia, engaged in the business of providing a discovery, influencer intelligence and analytics platform that enables brands, agencies, talent managers and other businesses to discover, analyse, and evaluate creators and influencers across various social media platforms.",
		"Please read these terms of service (“Terms”) carefully, as it contains the terms and conditions governing the User’s (defined below) use of the Platform, any content such as text, data, information, software, graphics, audio, video or photographs that the Company may make available through the Platform and any services that the Company may provide through the Platform. In order to use the Platform, the User must first agree to these Terms. By performing an affirmative action and thereafter, accessing the Platform, the User agrees and undertakes that the User is giving a free, specific, informed, unconditional and unambiguous consent to the Company, agreeing to these Terms and concluding a legally binding contract with the Company for the purposes specified herein. The User should not access or use the Platform if the User does not agree with any of the terms provided herein or is unable to be bound by them. As a condition of the User’s access to and use of the Platform, the User hereby agrees that the User will comply with all applicable laws and regulations when using the Platform.",
		"The Company reserves the right, at its sole discretion, to change, modify, add or remove portions of these Terms, at any time and will notify the User at least once in a year, or whenever there is a change in the Terms, as the case may be by email or by posting a conspicuous notice on the Platform. The User’s continued use of the Platform following the incorporation of such changes shall be deemed to mean that the User accepts and agrees to the revisions. As long as the User complies with these Terms, the Company grants the User a personal, non-exclusive, non-transferable, and limited privilege to access and use the Platform.",
		"The User should read these Terms and access and read all further linked information, if any, referred to in these Terms, as such information contains further terms and conditions that apply to the User as a user of the Platform. Such linked information including but not limited to the Company’s privacy policy (“Policy”) is hereby incorporated by reference into these Terms.",
		"If the User is unwilling or unable to be legally bound by these Terms, the User should not give his/her consent or use the Platform. The User cannot accept these Terms if: (a) the User is not lawfully entitled to use the Platform; or (b) if the User is less than 18 (Eighteen) years of age.",
	],
	sections: [
		{
			id: "terms-of-use",
			title: "Terms of Use",
			unnumbered: true,
			intro: [
				"For the purpose of these Terms, (a) all capitalised words and expressions defined by inclusion in quotation and/or parenthesis anywhere in these Terms, have the same meanings as ascribed to such words and expressions; and (b) wherever the context so requires, the following words and expressions shall bear the meanings ascribed to them below:",
			],
			bullets: [
				"“User” shall mean any person or entity who: (i) accesses or browses the Platform; or (ii) uses the Platform for the purpose of accessing the Services listed on the Platform.",
				"“Force Majeure Event” shall mean any event that is beyond the reasonable control of the Company and shall include, without limitation, sabotage, fire, flood, explosion, acts of God, civil commotion, strikes, lockouts or industrial action of any kind, riots, insurrection, war, acts of government, foreign or governmental order including orders of lock-down, quarantine, an outbreak of an epidemic, pandemic or other communicable diseases, computer hacking, civil disturbances, unauthorised access to computer data and storage device, computer crashes, breach of security and encryption, and any other similar events not within the control of the Company and which the Company is not able to overcome.",
			],
		},
		{
			id: "membership-eligibility",
			title: "Membership Eligibility",
			intro: [
				"Use of the Platform is available only to such natural persons and legal entities (acting through their duly authorised representatives) who can enter into legally binding contracts. In case of a natural person, persons who are “incompetent to contract”, including minors, un-discharged insolvents and persons of unsound mind, are not eligible to use the Platform. Any person under the age of 18 or with disability shall not register on the Platform and shall not transact on or use the Platform. If a minor or person with disability wishes to use or transact on the Platform, such use or transaction may be made by a verifiable consent by the minor/person with disability’s legal guardian or parents on the Platform. Any minor or person with disability accessing, using or transacting on the Platform in violation of these Terms shall be doing so at their own risk and the Company shall not be responsible or liable for any activities or interactions of such minor or person with disability on the Platform. The Company reserves the right to terminate any person’s membership in accordance with these Terms and/or refuse to provide such person with access to the Platform if it is brought to the notice of the Company or if the Company discovers for itself that such person is not eligible to use the Platform.",
			],
		},
		{
			id: "acceptance-of-terms",
			title: "Acceptance of Terms",
			clauses: [
				{
					text: "In order to use the Platform, the User must first agree to these Terms. The User can accept these Terms by:",
					items: [
						"registering with the Company via the Platform as a user; or",
						"by clicking to accept these Terms, when prompted on the Platform.",
					],
				},
			],
		},
		{
			id: "opening-an-account",
			title: "Opening an Account",
			clauses: [
				{ text: "The Platform allows only limited and restricted access to the services for unregistered users." },
				{ text: "In order to use the Platform, as part of the sign-up process, the User will have to create an account on the Platform (“Account”), which can be done by providing/using the following: (a) the e-mail address; (b) the Google or Apple ID; or (c) such other login credentials that are adopted by the Company from time to time and duly intimated to the User." },
				{
					text: "While signing-up with the Company to use the Platform, the User shall not:",
					items: [
						"create an Account for anyone other than the User, unless such person's prior permission has been obtained;",
						"use an Account that is the name of another person with the intent to impersonate that person; or",
						"create more than one Account on the Platform; or",
						"use multiple Accounts to fraudulently obtain or exploit any promotional credits, discounts, referral benefits or other promotional offers made available by the Company.",
					],
				},
				{ text: "The Company cannot and will not be liable for any loss or damage arising from the User’s failure to comply with this Clause." },
				{ text: "The User hereby confirms and undertakes that the information provided by the User while signing-up is and will be true, accurate, up-to-date, and complete at all times. The User agrees that if the User provides any information to the Company that is untrue, inaccurate, not up-to-date or incomplete or becomes untrue, inaccurate, not up-to-date or incomplete, the Company shall have the right to indefinitely suspend or terminate or block access to the Account on the Platform and refuse to provide the User access to the Platform." },
				{ text: "Once registered, the User can log in to the Account by using the e-mail address or mobile number provided at the time of signing-up and the one-time password (OTP) sent to their registered e-mail address or mobile number, by the Company from time to time (“Login Credentials”)." },
			],
		},
		{
			id: "account-confidentiality-obligations",
			title: "Account Confidentiality Obligations",
			clauses: [
				{ text: "The User agrees that the sole responsibility of maintaining the security and confidentiality of the Login Credentials rests with the User at all times. The User shall not share these Login Credentials with any third-party and the Company shall not be liable for any loss or damage arising from such breach." },
				{ text: "The Company reserves the right to take any and all action, as it deems necessary or reasonable, regarding the security of the Platform and the Account." },
				{ text: "The User is solely responsible for all activities that occur under the Account and/or the User undertakes on the Platform and hereby undertakes that no such activity shall be unlawful or in violation of any applicable laws, rules, and regulations." },
				{ text: "In no event and under no circumstances shall the Company be held liable for any liabilities or damages resulting from or arising out of the User’s use of the Platform or the Login Credentials, theft of the Login Credentials or release by the User of the Login Credentials to a third-party, or the User’s authorization to allow another person to access and use the Platform using the Account." },
				{ text: "In case of any misappropriation or unauthorized access of the Account, the User agrees to communicate the same to the Company immediately, in a manner indicated by the Company. The User shall further ensure that he/she exits/logs out from the Account at the end of each session. The Company shall not be liable for any loss or damage arising from the User’s failure to comply with this provision. The User may be held liable for any losses incurred by the Company or any other user of or visitor to the Platform due to authorized or unauthorized use of the Account, as a result of his/her failure in keeping the Login Credentials confidential." },
				{ text: "The User agrees that the information provided by the User to the Company, at all times (including during registration), will be true, accurate, up-to-date, and complete. The User further agrees that if he/she provides any information that is untrue, inaccurate, not up-to-date or incomplete or becomes untrue, inaccurate or incomplete or if the Company has reasonable grounds to suspect that such information is untrue, inaccurate, not up-to-date, incomplete or not in accordance with these Terms, the Company shall have the right to indefinitely suspend or terminate or block access to the Account on the Platform and refuse to provide the User access to the Platform. The User is advised to use due caution when providing any information to the Company accordingly." },
			],
		},
		{
			id: "services",
			title: "Services",
			clauses: [
				{ text: "The User will need to comply with these Terms (as applicable) in order to be able to use and access the services and widgets on the Platform, including powerful targeted discovery; creator analytics and media kit access, real-time creator comparisons; organized creator shortlists with import and export; structured talent intelligence; easy sharing; reusable creator pools and such other features as may be introduced by the Company, from time to time (“Services”)." },
				{ text: "The provision of Services on the Platform may be interrupted, including for maintenance, repairs, upgrades, or network or equipment failures. The Company strives to keep the Platform up and running; however, all online services suffer occasional disruptions and outages, and the Company isn’t liable for any disruption or loss the User may suffer as a result." },
				{ text: "The Company may discontinue some or all of the Services provided on the Platform, as it may deem fit, including certain features and the support for certain devices and platforms, at any time." },
				{ text: "It is being expressly clarified that the Users are solely responsible for managing their own accounts, campaigns, interactions with creators, brands, agencies, and/or talent managers, on the Platform (“End Users”)." },
				{ text: "The Company is not a party to, and shall have no responsibility or liability for, any contracts, donations, payments, or other commercial dealings between Users and End Users." },
				{ text: "Users must ensure compliance with all applicable consumer protection, taxation, and e-commerce laws and advertising, influencer marketing and other applicable regulatory requirements in connection with their interactions with End Users." },
				{ text: "Where the Platform facilitates subscriptions, payments or other commercial features, the Company acts solely as a technology platform and shall not be responsible for the underlying transaction, fulfilment of any obligations between Users and End Users, or the quality, legality or performance of any products or services offered by the Users." },
			],
		},
		{
			id: "use-of-the-platform",
			title: "Use of the Platform",
			clauses: [
				{
					text: "The User agrees, undertakes and covenants that, during the use of the Platform, the User shall not host, display, upload, modify, publish, transmit, store, update or share any information that:",
					items: [
						"belongs to another person or entity and to which the User does not have any right;",
						"is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, sexually-explicit (including nudity, implied nudity, excessive visible skin or cleavage, even if not explicitly sexual in nature, and any images focused on individual body parts, even if not explicitly sexual in nature), paedophilic, libellous, invasive of another person's privacy, insulting or harassing on the basis of gender, hateful or racially or ethnically objectionable, sensational, gory, depicting violence or threats of violence, relating or encouraging money laundering or gambling, or otherwise inconsistent or contrary to the laws in force in any manner whatsoever;",
						"could be construed as divisive/stereotyping and should be avoided if it could be interpreted as 'hateful' (Gender exclusive content is excluded from this, provided it is positive);",
						"is harmful to children/minors;",
						"is misleading in any way;",
						"involves the transmission of \"junk mail\", \"chain letters\", or unsolicited mass mailing or \"spamming\";",
						"infringes upon or violates any third-party's rights including, but not limited to, any patent, trademark, copyright or other proprietary rights or intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, e-mail address, physical address or phone number) or rights of publicity;",
						"contains assertions or implications about a person’s race, ethnic origin, religion, beliefs, age, sexual orientation or practices, gender identity, disability, medical condition (including physical or mental health), financial status. However, pro-equality content, particularly for gender and sexuality shall be permissible;",
						"impersonates another person or provides instructional information about illegal activities such as violating someone's privacy, or providing or creating computer viruses;",
						"provides information about any products, services, or content that are inappropriate, illegal, or unsafe, or that exploit, mislead, or exert undue pressure on the age groups targeted. This could include promotion of tobacco or tobacco-related products, recreational or medical marijuana, bongs and rolling papers;",
						"tries to gain unauthorized access or exceeds the scope of authorized access to the Platform or to profiles, blogs, communities, bulletins, or other areas of the Platform or solicits passwords or personally identifying information for commercial or unlawful purposes from other users of the Platform;",
						"engages in commercial activities without the Company’s prior written consent such as engages in contests, sweepstakes, barter, advertising etc.;",
						"exploits controversial political or social issues for commercial purposes;",
						"interferes with another user’s use of the Platform;",
						"refers to any Platform or URL that, in the Company’s sole discretion, contains material that is inappropriate for the Platform or any other Platform, contains content that would be prohibited or violates the letter or spirit of these Terms;",
						"deceives or misleads the addressee/users about the origin of the messages or knowingly and intentionally communicates any information which is patently false or misleading or grossly offensive or menacing in nature but may reasonably be perceived as a fact;",
						"serves to communicate fake, inaccurate or misleading information including fake, inaccurate or misleading news or facts;",
						"contains software viruses or any other computer codes, files or programs designed to interrupt, destroy or limit the functionality of any computer resource;",
						"threatens the unity, integrity, defence, security or sovereignty of the nation, friendly relations with foreign States, or public order, or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting other nation;",
						"is patently false and untrue, and is written or published in any form, with the intent to mislead or harass a person, entity or agency for financial gain or to cause any injury to any person;",
						"contains any trojan horses, worms or other computer programming routines that may damage, detrimentally interfere with, diminish value of, covertly intercept or steal any system, data or personal information of another visitor;",
						"is in the nature of an online game that is not verified as a permissible online game;",
						"is in the nature of advertisement or surrogate advertisement or promotion of an online game that is not a permissible online game, or of any online gaming intermediary offering such an online game; or",
						"violates any law for the time being in force.",
					],
				},
				{ text: "The User agrees and acknowledges that: (a) the User shall not use the Platform for any illegal or unauthorized purpose; and (b) the User’s use of any information or materials on the Platform is entirely at the User’s own risk, for which the Company shall not be liable. The User agrees to comply with all laws, rules and regulations applicable to the use of the Platform." },
				{ text: "The User hereby accepts full responsibility for any consequences that may arise from his/her use of the Platform, and expressly agree and acknowledge that in no event and under no circumstances the Company be held liable to the User for any liabilities or damages resulting from or arising out of the User’s use of the Platform." },
				{ text: "The Company shall have the right, but not the obligation, to monitor access to or use of the Platform to ensure the User’s compliance with these Terms or applicable laws or other legal requirements, at its sole discretion." },
			],
		},
		{
			id: "user-s-posts-and-reviews",
			title: "User's Posts and Reviews",
			clauses: [
				{ text: "The Platform may allow the User to post certain content, data or information belonging to the User, such as creator profiles, campaign information, reviews, ratings, comments, posts, photographs, videos, as well as submit/post any photos, videos, suggestions, comments, questions or other information to the Company using the Platform (collectively referred to “User Content”). Provided however that, before being published on the Platform, such User Content shall be reviewed by the Company to ensure compliance with these Terms and applicable laws." },
				{ text: "The User, being the originator of the User Content, is responsible for the User Content that the User uploads, posts, publishes, transmits or otherwise makes available on the Platform. The User represents that the User exclusively owns the copyright in the User Content and has obtained all relevant consents and approvals in order to post any User Content. The User further represents that all such User Content will be in accordance with applicable law and shall not post any content relating to or owned by a third-party for the promotion or sale of products of such third-party. The User acknowledges that the Company does not endorse any User Content on the Platform and is not responsible or liable for any User Content. The Company reserves the right to remove any third-party marketing material and disable access to the User Content on the Platform." },
				{ text: "In case a third-party appears in a User Content, the User confirms that the User has obtained prior consent of such third-party before uploading or posting such User Content. The User further agrees that the User shall indemnify the Company against any and all claims raised by such third-party with respect to the User Content." },
				{ text: "The User hereby grants the Company a perpetual, non-revocable, worldwide, royalty-free and sub-licensable right and license to use, copy, distribute, display, publish, transmit, make available, reproduce, modify, adapt the User Content and create derivative works of the User Content in any manner as deemed appropriate by the Company in any form including but not limited to print, broadcast, online and across any and all Platforms owned by the Company, any and all platforms owned by the Company on any social media channels including but not limited to Instagram, Facebook and Twitter." },
				{ text: "The User represents and warrants that the User owns or otherwise controls all of the rights to the User Content that the User posts or that the User otherwise provides on or through the Platform; and that, as at the date that the User Content is posted or submitted on the Platform: (a) the User Content is accurate; (b) use of the User Content the User supplies does not breach these Terms; and (c) such User Content is lawful." },
				{ text: "The User further represents and warrants that while posting any User Content on the Platform, the User shall not use any offensive, libellous, derogatory, hateful or racially or ethnically objectionable language. Further, the User shall not post any content on the Platform that is obscene, pornographic, constitutes an “indecent representation of women” as provided in The Indecent Representation of Women (Prohibition) Act, 1986." },
			],
		},
		{
			id: "payment-facility-and-credits",
			title: "Payment Facility and Credits",
			clauses: [
				{ text: "The Platform permits payment via various modes, including virtual payment wallets and online payments through debit/credit cards and internet banking or any other method adopted by the Company from time to time." },
				{
					text: "While availing any of the payment method/s available on the Platform, the Company will not be responsible for or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to the User due to:",
					items: [
						"Lack of authorization for any transaction(s);",
						"Exceeding the pre-set limit mutually agreed by the User and between bank/s;",
						"Any payment issues arising out of the transaction;",
						"Rejection of transaction for any other reason(s) whatsoever.",
					],
				},
				{ text: "All payments made for the subscription plans, Services or other paid offerings available on the Platform by the User shall be in Indian Rupees or such other currency as may be permitted by the Company from time to time, and shall be exclusive of applicable Goods and Services Tax (GST) or any other applicable statutory taxes, levies, or charges, which shall be payable by the User. It is expressly clarified that the Company will not facilitate transactions with respect to any other form of currency with respect to the purchases made on the Platform, except as expressly permitted by the Company." },
				{ text: "All payments made are non-refundable." },
				{ text: "If a User has subscribed through the Apple App Store, the billing and refund policies of such platform shall apply." },
				{ text: "The Company reserves the right to modify the subscription fees, and shall provide the Users, at least 30 (Thirty) days’ prior notice of any such change." },
				{ text: "The User acknowledges that the Company will not be liable for any damages, interests or claims, losses resulting from or suffered on account of not processing a transaction/transaction amount or any delay in processing a transaction/ transaction amount which is beyond the control of the Company." },
				{ text: "Upon making payment of the fees as indicated by the Company, the User shall have purchased credits equivalent to the amount of fees paid (“Credits”). Each Credit shall represent a value as determined and notified by the Company from time to time." },
				{ text: "The Credits may be utilized in the manner specified by the Company to access paid offerings and premium features available on the Platform. Credits are non-transferable and cannot be redeemed or exchanged for cash or any monetary value." },
				{ text: "Upon utilization of the Credits, the User may recharge the Credits by making payment of the applicable fees in order to continue availing the paid features and offerings of the Platform." },
				{ text: "The Credits shall remain valid for the duration of the User's active subscription or plan. Where the User renews or recharges the applicable plan, any unused Credits shall automatically roll over to the renewed or recharged plan, or shall be treated in accordance with the Company’s prevailing policy in relation to Credits, as may be amended from time to time. However, if the User fails to renew or recharge the applicable plan, any unused Credits shall automatically lapse and stand forfeited, without any obligation on the Company to provide any notice, refund or compensation in respect thereof." },
			],
		},
		{
			id: "agreement-to-receive-communication",
			title: "Agreement to Receive Communication",
			intro: [
				"The Platform may from time to time submit a request to the User to the receipt of communication from the Company by way of in-app notifications, WhatsApp, Instagram, Telegram, Short Message Service (SMS), voice calls, video calls, e-mails and other digital communications. These emails and messages could relate to the User’s registration and/or activities that the User carries out through the Platform, Services and promotions that are undertaken by the Company and its third-party partners.",
			],
		},
		{
			id: "links-to-third-party-platforms",
			title: "Links to Third-Party Platforms",
			intro: [
				"The Platform may contain links and interactive functionality interacting with the websites, platform or services of third-parties. The Company is not responsible for and has no liability for the functionality, actions, inactions, privacy settings, privacy policies, terms, or content of any such websites, platforms or services. Before enabling any sharing functions to communicate with any such websites, platforms or services or otherwise visiting any such websites, platforms or services, the Company strongly recommends that the User reviews and understands the terms and conditions, privacy policies, settings, and information-sharing functions of each such third-party websites, platform or service.",
			],
		},
		{
			id: "open-source-components",
			title: "Open-Source Components",
			intro: [
				"The Platform may include open-source software components, each of which shall be governed by its respective license terms. In the event of any inconsistency between the license terms of an open-source component and these Terms, the open-source license terms shall prevail with respect to that specific component, and the User’s rights and obligations regarding such component shall be governed accordingly.",
			],
		},
		{
			id: "representations",
			title: "Representations",
			intro: [
				"The User hereby represents and warrants that the User has validly entered into these Terms and has the legal power to do so. The User further represents and warrants that the User shall be solely responsible for the due compliance with these Terms.",
			],
		},
		{
			id: "limitation-of-liability",
			title: "Limitation of Liability",
			clauses: [
				{ text: "The User hereby acknowledges that the Company shall not be held liable to the User for any special, consequential, incidental, and exemplary or punitive damages, or loss of profit or revenues." },
				{ text: "The Company shall also not be liable under any circumstance for damages arising out or related in any way to: (a) any errors, mistakes, or inaccuracies of content, creator profiles, analytics, insights or other information made available through the Platform; (b) any unauthorized access to or use of the secure servers and/or any and all personal and/or other user information stored therein; (c) any interruption or cessation of transmission to or from the Services on the Platform or the failure of the Services to remain operational for any period of time; (d) any bugs, viruses, trojan horses, or the like, which may be transmitted to or through the Platform by any third-party; (e) any loss of the User’s data arising from any use of or inability to use any parts of the Platform; (f) non-availability of the Services in certain geographical areas; and/or (g) any errors or omissions in any content or for any loss or damage of any kind incurred as a result of the use of any content posted, emailed, transmitted, or otherwise made available via the Platform, whether based on warranty, contract, tort, or any other legal theory, and whether or not the Company is advised of the possibility of such damages." },
				{ text: "The Company shall not be liable under any circumstances for damages arising out of or in any way related to the Services and/or information offered or provided by third-party vendors, through the Platform." },
			],
		},
		{
			id: "disclaimer-of-warranties",
			title: "Disclaimer of Warranties",
			intro: [
				"The Platform and all information, content, materials and services included on or otherwise made available to the user through the Platform (collectively, \"Contents\") are provided by the company on an \"as is,\" \"as available\" basis, without representations or warranties of any kind. The Company makes no representations or warranties of any kind, express or implied, as to the operation of the Platform, the accuracy or completeness of the Contents, including any creator profiles, analytics, insights, metrics or other information made available through the Platform, and the accuracy of the information. The Company shall have no responsibility for any damage to the User’s computer system or loss of data that results from the download of any content, materials, document or information. The User expressly agrees that the use of the Platform is at the User’s sole risk. The Company will not be liable for any damages of any kind arising from the use of the Platform or the contents including, without limitation, direct, indirect, consequential, punitive, and consequential damages, unless otherwise specified in writing. To the full extent permitted by law, the Company disclaims any and all representations and warranties with respect to the Platform and its Contents, whether express or implied, including, without limitation, warranties of title, merchantability, and fitness for a particular purpose or use.",
			],
		},
		{
			id: "indemnification",
			title: "Indemnification",
			intro: [
				"The User shall indemnify and hold harmless the Company, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees, from any and all claims or demands, or actions including reasonable attorneys' fees, made by any third-party or penalty imposed due to or arising out of the User’s breach of these Terms, Policy and other policies, or the User’s violation of any law, rules or regulations or the rights (including infringement of any intellectual property rights) of a third-party.",
			],
		},
		{
			id: "content-and-intellectual-property-rights",
			title: "Content and Intellectual Property Rights",
			clauses: [
				{ text: "Other than: (a) User Content, and (b) the trademarks, logos and service marks displayed on the Platform that are the property of other third-parties, the Company solely and exclusively owns copyrights, trademarks, service marks, logos, trade names, and other intellectual and proprietary rights associated with the Company’s services provided on the Platform and Contents, including the Company's software, artificial intelligence models, algorithms, analytics, insights, databases and other proprietary technology (“Platform Content”)." },
				{ text: "Through the User’s use of the Platform, by no means are any rights impliedly or expressly granted to the User in respect of such Platform Content. The Company reserves the right to change or modify the Services and/or the Platform Content (as the case may be) from time to time at its sole discretion." },
				{ text: "The User hereby acknowledges that the Platform Content and the Services constitute original works and have been developed, compiled, prepared, revised, selected, and arranged by the Company and others through the application of methods and standards of judgment developed and applied through the expenditure of substantial time, effort, and money and constitutes valuable intellectual property of the Company and such others. The User thereby agrees to protect the proprietary rights of the Company and such others during and after the term of these Terms. The User may not selectively download portions of the Platform without retaining the copyright notices. The User may download material from the Platform only for the User’s own personal use and for no commercial purposes whatsoever." },
				{ text: "The User shall use the Platform strictly in accordance with these Terms, and shall not, directly or indirectly: (a) decompile, disassemble, reverse engineer, or attempt to derive the source code of, or in any manner decrypt, the Platform; (b) make any modification, adaptation or improvement, enhancement, translation or derivative work from the Platform; (c) violate any applicable laws, rules or regulations in connection with his/her access or use of the Platform, including his/her use of any Platform Content; (d) remove or obscure any proprietary notice (including any notices of copyright or trademark) forming a part of the Platform; (e) use the Platform for any commercial or revenue generation endeavours, or other purposes for which it is not designed or intended; (f) distribute or transmit the Platform or other services; (g) use the Platform for data mining, scraping, crawling, harvesting, automated extraction or collection of data, redirecting, or for any purpose not in accordance with these Terms; (h) use the Platform for creating a service or software that is directly or indirectly, competitive with the Platform or any Services; or (i) derive any confidential information, processes, data or algorithms from the Platform." },
				{ text: "Any infringement shall lead to appropriate legal proceedings against the User at appropriate forum for seeking all available remedies under applicable laws of the country." },
			],
		},
		{
			id: "privacy-policy",
			title: "Privacy Policy",
			intro: [
				"The User should review the Policy, which also governs the User’s visit to the Platform, to understand the Company’s privacy practices. The information/data provided to the Company by the User during the course of usage of the Platform will be treated as strictly confidential and in accordance with the Policy and applicable laws and regulations. If the User objects to the User’s information being transferred or used, the User is advised not to use the Platform.",
			],
		},
		{
			id: "assignment",
			title: "Assignment",
			intro: [
				"The User shall not license, sell, transfer or assign User’s rights, obligations, or covenants under this Terms in any manner without the Company’s prior written consent. The Company reserves the right, at its own discretion, to freely assign and transfer the rights and obligations under this Terms to any third-party.",
			],
		},
		{
			id: "governing-law-and-dispute-resolution",
			title: "Governing Law and Dispute Resolution",
			intro: [
				"This Terms shall be governed by and interpreted and construed in accordance with the laws of India. The place of jurisdiction shall exclusively be in Bengaluru. In the event of any dispute arising out of this Terms, the same shall be settled by a binding arbitration conducted by a sole arbitrator, appointed jointly by both parties and governed by the Arbitration and Conciliation Act, 1996, as amended from time to time. The seat and venue of arbitration shall be Bengaluru.",
			],
		},
		{
			id: "severability-and-waiver",
			title: "Severability and Waiver",
			intro: [
				"These Terms, the Policy and other referenced material herein or on the Platform, are the entire agreement between the User and the Company with respect to the Services offered on the Platform, and supersede all prior or contemporaneous communications and proposals (whether oral, written or electronic) between the User and the Company with respect thereto and govern User’s future relationship with the Company. If any provision of this Terms is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that this Terms will otherwise remain in full force and effect and enforceable. The failure of either party to exercise in any respect any right provided for herein shall not be deemed a waiver of any further rights hereunder.",
			],
		},
		{
			id: "grievance-redressal-mechanism",
			title: "Grievance Redressal Mechanism",
			intro: [
				"For registering the User’s concerns, complaint or grievances, please write to the below mentioned designated officer of the Company at the below-mentioned email address in relation to any violation of these Terms or the applicable laws. The designated officer shall redress the concerns, complaint or grievances in accordance with the applicable laws.",
			],
			contact: GRIEVANCE_ROWS,
		},
		{
			id: "how-to-contact-us",
			title: "How to Contact Us",
			intro: [
				`If the User has any questions or concerns about this Terms, the User may contact the Company at the following email address: ${LEGAL_CONTACT_EMAIL}`,
			],
		},
	],
};
